### ISSUE TITLE
Which elfinder?

### ISSUE THREAD

**Issue by ghost** [nao-pon/elFinder#8]
I have found elfinder after a search for some filemanager with HTML5 and PHP. According to elfinder.org, the latest version is about 1 year old, i dont know if this is maintained anymore. But i have seen, that you have contributed some newer code, so i dont know which one to choose. 

Is your elfinder a newer version/fork of the original one?

I have read something about Dropbox Support. Could you please give some advice, how i can use this? Is it possible to add Google Drive, WebDAV and SkyDrive to?

**Comment by nao-pon** [comment]
Hi, bilbob74.

elFinder's main stream is"[Studio-42/elFinder:2.x](https://github.com/Studio-42/elFinder)". "[Studio-42/elFinder:2.1](https://github.com/Studio-42/elFinder/tree/2.1)" has added some new functions, such as S3 driver, to 2.x.

Those development is succeedingly performed, although speed became slow. 

I add the graphics editing function in a Dropbox driver and pixlr, etc. to elFinder 2.x, and am developing as 2.x_n. 
It is 2.1_n which merged 2.1 into the 2.x.

Since the driver has not been made yet, Google Drive and WebDAV and SkyDrive cannot be used. 
However, use will become possible if someone makes those drivers.

Refer to the following link place for the usage of the Dropbox driver of "2.x_n" or "2.1_n".
- https://github.com/Studio-42/elFinder/pull/282#issuecomment-18714039
  - Please access to https://www.dropbox.com/developers/apps/create, and set "Full Dropbox" and choice "Core" & "Full Dropbox".
  - define 'ELFINDER_DROPBOX_CONSUMERKEY' & 'ELFINDER_DROPBOX_CONSUMERSECRET' in connector.php
  - Use  "Network volume mount". Please check next video. http://youtu.be/S1Q_jGIwrzY

**Comment by ghost** [comment]
Thanks for your tips. I have created a App in my Dropbox, but i only get from Dropbox a App Key and a App Secret. Here are my Steps:

GoTo https://www.dropbox.com/developers/apps/create
Select Core, Type some Name, choose "Full Dropbox" and click the Button "Create App"
Now on the new page, i see a App Key and a App Secret, i copyed this to connector.php
Now in eLFinder i click on netmount, choose Dropbox and connect to My Dropbox
This seems to work, but now i click on Mount and get the following error: 

Unable to mount "dropbox".
Cache dirctory (metaCachePath or tmp) is require.

**Comment by nao-pon** [comment]
Dropbox root driver need a writable directory for data catch. The driver discovery form driver options 'tmbPath' or 'tmpPath' or 'metaCachePath'. Among those, something should set up one.　;-)

**Comment by ghost** [comment]
Got it to work after set metaCachePath in elFinderVolumeDropbox.class.php directly

**Comment by nao-pon** [comment]
I added new constant 'ELFINDER_DROPBOX_META_CACHE_PATH' for `options['metaCachePath']` . You can set 'metaCachePath' on connector.php. (aecd8d7891537a92b05d4ad024a252afc344b613)

ex.

``` php
define('ELFINDER_DROPBOX_CONSUMERKEY',    'xxxxxxxxxxxxxxxxxxxxxxx');
define('ELFINDER_DROPBOX_CONSUMERSECRET', 'xxxxxxxxxxxxxxxxxxxxxxx');
define('ELFINDER_DROPBOX_META_CACHE_PATH','PATH TO "metaCachePath"'); // optional for `options['metaCachePath']`
```
